version: '3'
services:
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./pic-sure-auth-ui/src/main/webapp:/usr/local/apache2/htdocs
      - ./pic-sure-auth-ui/target/webjars/META-INF/resources/webjars:/usr/local/apache2/htdocs/psamaui/webjars
      - ./pic-sure-auth-ui/src/main/resources:/usr/local/apache2/htdocs/psamaui/settings
    networks:
      - public

  picsureauth:
    build:
      context: pic-sure-auth-services
      dockerfile: Dockerfile
    command: --debug *:8787
    depends_on:
      - picsureauthdb
    environment:
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET:-secret}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID:-client_id}
      - AUTH_USER_ID_CLAIM = sub
      - AUTH_MYSQLADDRESS=picsureauthdb
      - AUTH0TOKEN=${AUTH0TOKEN:-nothing}
      - AUTH0HOST=https://avillachlab.auth0.com
      - MAIL_PASSWORD=${MAIL_PASSWORD:-password}
      - systemName=${systemName:-PICSURE}
    ports:
      - 8080:8080
      - 8787:8787
    expose:
      - 8080
    networks:
      - public

  picsureauthdb:
    build:
      context: pic-sure-auth-db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${AUTH_MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=auth
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - picsure-auth-data:/var/lib/mysql
    networks:
      - public

networks:
  public:

volumes:
  picsure-auth-data:
